Revert "fix: Tratativa em corrigir AttributeError: 'int' object has no attribute 'value'"
This reverts commit 7cd65e7dae3eaf8f269c88c5b700f9e38c7e3b54.